---
apiVersion: v1
kind: Namespace
metadata:
  name: plantkart

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: plantkart
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: plantkart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: plantkartdb
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: plantkart
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: plantkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 176087999593.dkr.ecr.ap-south-1.amazonaws.com/plantkart-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/plantkartdb
            - name: JWT_SECRET
              value: devsecret
            - name: STRIPE_SECRET_KEY
              value: sk_test_replace
            - name: CLIENT_BASE_URL
              value: http://frontend:80

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: plantkart
spec:
  type: ClusterIP
  ports:
    - port: 4000
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: plantkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 176087999593.dkr.ecr.ap-south-1.amazonaws.com/plantkart-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE
              value: http://backend:4000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: plantkart
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plantkart-ingress
  namespace: plantkart
spec:
  ingressClassName: nginx
  rules:
    - host: plantkart.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
